### ISSUE TITLE
Why you removed Jodd from the list?

### ISSUE THREAD

**Issue by igr** [jaapcoomans/microframeworks#13]
Just wonder - why you have removed Jodd from the powerpoint presentation? Just curious to know the reasons.

**Comment by jaapcoomans** [comment]
Hi @igr. The reason is that Jodd is actually a set of microframeworks. It's not very comparable to all the other candidates. The part of Jodd that I figured came closest to the others is Joy. That unfortunately is barely documented. Looking at it now I see maybe Madvoc could have been wordt looking at.

**Comment by igr** [comment]
Yeah, no worries, just wanted to know how did you understand it how do you see it.

Yes, you can use each part independently - but of course, the idea in the terms you are examining, is to use the whole bundle, hence the `Joy` is there, that combines everything in one. For the point of your presentation, the `joy` is what should be examined.

But again, please don't bother. I am fully aware Jodd can't compare to others. I am just a single dev and documentation is really bad :)
