### ISSUE TITLE
Armeria feed back?

### ISSUE THREAD

**Issue by trustin** [jaapcoomans/microframeworks#14]
Hi @jaapcoomans,

I'm the lead of [Armeria project](https://line.github.io/armeria). I found your repository from GitHub's dependency network. Did you have a chance to review Armeria as a microservice framework? If so, what pros and cons did you find? What improvements would you want from us?

**Comment by trustin** [comment]
I obviously forgot to say thank you for working on this repository and trying to make reasonable comparison. Please keep up the great work!

**Comment by jaapcoomans** [comment]
Hi Trustin,
Good to see you actively collecting feedback. We already had a conversation via Twitter on this topic when you encountered the slides that belong to this repo :) 

https://twitter.com/trustin/status/1256566157709938688?s=19

I haven't worked with Armenia or my talj since. But my promise still stands to take a fresh look at it when I get another chance to present this talk.

**Comment by trustin** [comment]
Oh, hey. Didn't notice this repository is from you. Thanks!
